<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add project' => 'Ajouter un projet',
    'Add your project to receive Tunisia Impact COIN that you can use to reward your donors and supporters.' => 'Ajoutez votre projet pour recevoir Tunisia Impact COIN que vous pourrez utiliser pour récompenser vos donateurs et supporteurs.',
    'As a collaboration and value exchange platform we are using Coinsence.org platform. By clicking the button above, you agree to Coinsence {0}Terms of services{1} and have read and acknowledge Coinsence {2}Privacy Policy{3}' => 'En tant que plate-forme de collaboration et d\'échange de valeur, nous utilisons la plate-forme Coinsence.org. En cliquant sur le bouton ci-dessus, vous acceptez les {0}Conditions d\'utilisation{1} de Coinsence et avez lu et reconnu la {2}Politique de confidentialité{3}',
    'Check our project and get for your financial support your reward in Tunisia Impact COIN.' => 'Consultez notre projet et obtenez pour votre soutien financier votre récompense en Tunisie Impact COIN.',
    'Create' => 'Créer',
    'Fund' => 'Financer',
    'Fund project' => 'Financer le projet',
    'Initiated by Tunisian diaspora and local change-makers with the vision to Remove borders and build an open and decentral governed collaboration network that stimulates a more inclusive and sustainable economy that is build on participation and sharing.' => 'Initié par la diaspora tunisienne et les acteurs locaux du changement avec la vision de supprimer les frontières et de construire un réseau de collaboration gouverné ouvert et décentralisé qui stimule une économie plus inclusive et durable qui repose sur la participation et le partage.',
    'Join us' => 'Rejoignez-nous',
    'Offer your expertise, products, services or discounts and receive Tunisia Impact COIN as compensation.' => 'Offrez votre expertise, produits, services ou remises et recevez Tunisia Impact COIN comme compensation.',
    'Powered By:' => 'Powered By:',
    'Start now' => 'Commencer maintenant',
    'Support' => 'Supporter',
    'Welcome to our community' => 'Bienvenue dans notre communauté',
    '{0} We are {1} a global network of {2} Innovators & {3} social entrepreneurs.' => '{0} Nous sommes {1} un réseau mondial de {2} innovateurs et {3} entrepreneurs sociaux.',
];
