<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Accounts' => 'Comptes',
    'Active spaces' => 'Espaces actifs',
    'Activity Stream' => 'Page d\'activités',
    'Campaigns' => 'Campagnes',
    'Check and update your personal profile.' => 'Vérifiez et mettez à jour votre profil personnel.',
    'Check for current funding campaigns.' => 'Trouver les campagnes de financement en cours.',
    'Find other members within the network.' => 'Trouver d\'autres membres au sein du réseau.',
    'Find products, services and ressources.' => 'Rechercher des produits, des services et des ressources.',
    'Find projects, organizations and communities.' => 'Trouvez des projets, des organisations et des communautés.',
    'Marketplace' => 'Marché',
    'People' => 'Personnes',
    'Profile' => 'Profil',
    'Search' => 'Rechercher',
    'Search for people, spaces or content using keywords.' => 'Rechercher des personnes, des espaces ou du contenu à l\'aide de mots-clés.',
    'See all your accounts, balances and transactions.' => 'Voir vos comptes, soldes et transactions.',
    'See what the members are posting.' => 'Voyez ce que les membres publient.',
    'Shortcuts' => 'Raccourcis',
    'Spaces' => 'Espaces',
];
