<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add your project' => '',
    'Add your project and receive funding in IBB COINs to reward your donors and supporters.' => '',
    'As a collaboration and value exchange platform we are using Coinsence.org platform. By clicking the button above, you agree to Coinsence {0}Terms of services{1} and have read and acknowledge Coinsence {2}Privacy Policy{3}' => '',
    'Check the marketplace' => '',
    'Check the projects' => '',
    'Create' => '',
    'Fund' => '',
    'Initiated by Tunisian diaspora and local change-makers with the vision to build an open collaboration network that supports impact projects and enables value sharing across all borders.' => '',
    'Join us' => '',
    'Offer your expertise, products, services or discounts and receive IBB COINs as compensation.' => '',
    'Powered By:' => '',
    'Support' => '',
    'Support your selected projects with some funding and get rewarded through IBB COINs.' => '',
    'Welcome to our community' => '',
    '{0} We are {1} a global network of {2} Innovators & {3} social entrepreneurs.' => '',
];
