<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'A knowledge resources and materials directory.' => 'دليل مصادر المعرفة والمواد',
    'Learn the Sharing Economy basics.' => 'تعلم أساسيات اقتصاد المشاركة',
    'Accounts' => 'الحسابات',
    'Active spaces' => 'الفضاءات النشطة',
    'Activity Stream' => 'صفحة النشاط',
    'Campaigns' => 'الحملات',
    'Check and update your personal profile.' => 'رؤية وتحديث ملف التعريف الشخصي الخاص بك',
    'Check for current funding campaigns.' => 'انظر حملات التمويل الحالية',
    'Find other members within the network.' => 'ابحث عن أعضاء آخرين داخل الشبكة',
    'Find products, services and ressources.' => 'البحث عن المنتجات والخدمات والموارد',
    'Find projects, organizations and communities.' => 'ابحث عن المشاريع والمنظمات والمجتمعات',
    'Knowledge Souk' => 'سوق المعرفة',
    'Marketplace' => 'السوق',
    'People' => 'الأعضاء',
    'Profile' => 'الملف الشخصي',
    'Search' => 'بحث',
    'Search for people, spaces or content using keywords.' => 'ابحث عن أشخاص أو مساحات أو محتوى باستخدام الكلمات الرئيسية.',
    'See all your accounts, balances and transactions.' => 'اطلع على جميع حساباتك وأرصدةك ومعاملاتك',
    'See what the members are posting.' => 'انظر ما ينشره الأعضاء',
    'Sharing Economy Crash Course' => 'كورس الاقتصاد التشاركي',
    'Shortcuts' => 'الاختصارات',
    'Spaces' => 'الفضاءات',
];
