<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add project' => '',
    'Add your project to receive Tunisia Impact COIN that you can use to reward your donors and supporters.' => '',
    'As a collaboration and value exchange platform we are using Coinsence.org platform. By clicking the button above, you agree to Coinsence {0}Terms of services{1} and have read and acknowledge Coinsence {2}Privacy Policy{3}' => '',
    'Check our project and get for your financial support your reward in Tunisia Impact COIN.' => '',
    'Create' => '',
    'Fund' => '',
    'Fund project' => '',
    'Initiated by Tunisian diaspora and local change-makers with the vision to Remove borders and build an open and decentral governed collaboration network that stimulates a more inclusive and sustainable economy that is build on participation and sharing.' => '',
    'Join us' => '',
    'Offer your expertise, products, services or discounts and receive Tunisia Impact COIN as compensation.' => '',
    'Powered By:' => '',
    'Start now' => '',
    'Support' => '',
    'Welcome to our community' => '',
    '{0} We are {1} a global network of {2} Innovators & {3} social entrepreneurs.' => '',
];
