<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'A knowledge resources and materials directory.' => '',
    'Accounts' => '',
    'Active spaces' => '',
    'Activity Stream' => '',
    'Campaigns' => '',
    'Check and update your personal profile.' => '',
    'Check for current funding campaigns.' => '',
    'Find other members within the network.' => '',
    'Find products, services and ressources.' => '',
    'Find projects, organizations and communities.' => '',
    'Knowledge Souk' => '',
    'Learn the Sharing Economy basics.' => '',
    'Marketplace' => '',
    'People' => '',
    'Profile' => '',
    'Search' => '',
    'Search for people, spaces or content using keywords.' => '',
    'See all your accounts, balances and transactions.' => '',
    'See what the members are posting.' => '',
    'Sharing Economy Crash Course' => '',
    'Shortcuts' => '',
    'Spaces' => '',
];
